version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: lifemoments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
      args:
        - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/lifemoments
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/lifemoments
      - ALLOWED_ORIGINS=http://localhost:3000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - LOCATIONIQ_API_KEY=${LOCATIONIQ_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: