
services:
  - type: web
    name: ltbe-v100-jse247
    runtime: docker            # prefer 'runtime' over legacy 'env'
    plan: starter
    rootDir: backend
    dockerfilePath: ./Dockerfile  # path is relative to repo root
    dockerContext: .              
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ltdb-v100-jse247
          property: connectionString
      - key: ALLOWED_ORIGINS
        # Set this in Render dashboard Environment Variables
        # Example: 'https://your-frontend-url.onrender.com,http://localhost:3000'
      - key: AWS_ACCESS_KEY_ID
      - key: AWS_SECRET_ACCESS_KEY
      - key: AWS_BUCKET_NAME
      - key: AWS_REGION
        value: us-east-1
      - key: LOCATIONIQ_API_KEY
      - key: OPENAI_API_KEY
        
    healthCheckPath: /health

  - type: web
    name: ltfe-v100-jse247
    runtime: docker
    plan: starter
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        # Set this in Render dashboard Environment Variables  
        # Example: https://your-backend-url.onrender.com
      - key: NEXT_PUBLIC_DEBUG
        value: false

databases:
  - name: life-moments-db
    plan: free

