
FROM python:3.11-slim

WORKDIR /app

# dependency for pg access.
RUN apt-get update && apt-get install -y --no-install-recommends build-essential libpq-dev && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app

# Do NOT set ENV PORT; Render provides it.
CMD ["sh","-c","uvicorn app.main:app --host 0.0.0.0 --port ${PORT}"]
